# Generated by Django 3.0 on 2020-12-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
